[package]
name = "firstchar"
version = "1.1.0"
edition = "2021"

description = "A utility to shorten each word to its first character for memorization (maintaining punctuation)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
